### ISSUE TITLE
Can't find string resource when using productFlavors

### ISSUE THREAD

**Issue by fryossi** [luggit/react-native-config#182]
I'm getting "No resource found" error for task 'app:process<productFlavor>DebugResources'  while trying to sync gradle.
It fails on generating AndroidManifest file.
It was okay until adding flavors.
I have `resValue "string", "build_config_package", <myBasePackageName>` on the `defaultConfig`.
**EDIT:** myBasePackageName as in the Manifest file.
react-native-config: 0.10.0.
What am i doing wrong?
Thanks

**Comment by pedro** [comment]
Hey there! Sorry for the trouble I believe this was fixed in 0.11.1 – can you give it a try?

Thanks,

**Comment by fryossi** [comment]
Still the same. just to clarify the issue- the build with `ENVFILE=.env.dev react-native run-android --variant=<variantName>Debug` works fine. the problem is when i'm trying to sync project with gradle(in android studio).

**Comment by pedro** [comment]
Oops, should be fixed for good now 😬 
Sorry for the trouble
