### ISSUE TITLE
Modified variables are not updated after rebuilding

### ISSUE THREAD

**Issue by mickael-h** [luggit/react-native-config#591]
I keep changing variable values in the .env file, but recompiling the app doesn't change anything (at least on iOS)
I tried cleaning every cache I could think of, but the config values are still the same as the first build.
Could you give instructions in order to clean the .env cache?

**Comment by VinitSarvade** [comment]
@mickael-h Faced the same issue, fixed it by clearing the xcodederiveddata in your system.

**Comment by sahildeliwala** [comment]
Try running `react-native start --reset-cache`
running start command with --reset-cache forces the rebuild bundle with updated env variables.

**Comment by hke-ghtest2** [comment]
Faced the same issue, every time need to manually remove node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m.

Any updates on the handling?

**Comment by pvroosendaal** [comment]
Just removing the GeneratedDotEnv.m file didn't help me, that caused a compile error, because the import then fails in  ReactNativeConfig.m, line 2. Running "Clean Build Folder" in Xcode works for me.

**Comment by hke-ghtest2** [comment]
@pvroosendaal , thanks for that update. 
Yes `Running "Clean Build Folder" in Xcode ` also works for me .
I think this is the better way for refreshing the cached content.

**Comment by billnbell** [comment]
how about another solution ?

**Comment by billnbell** [comment]
https://github.com/luggit/react-native-config/pull/699

**Comment by rafaelmaeuer** [comment]
in my case https://github.com/luggit/react-native-config/issues/710 helps

**Comment by Stas-Buzunko** [comment]
running Running "Clean Build Folder" in Xcode does work. 
But it's ridiculous we have to Clean build folder each time (we pass commit hash on build so env changes on each deployment) + ENVFILE path is ignored and we have to copy env file we need to .env. This library has ~250 opened issues, no idea how it's still the most popular lib for handling env variables...

i think it's time to switch to another library as we have wasted too much time on this one. Going to try react-native-dotenv, i don't think it could be worse than this one 🤣

**Comment by luancurti** [comment]
Fixed in `1.4.12`

**Comment by robsonos** [comment]
Just tested here and it still does not update environment variables after rebuilding the code

**Comment by alessioemireni** [comment]
Same to me. We need to reopen this issue. With 1.4.12 version I have to Clean the Build folder.

**Comment by alessioemireni** [comment]
Same here. We need to reopen the issue.
The error occurs the second time. Example:
`ENVFILE=.env.production yarn ios `--> OK
`ENVFILE=.env.production yarn ios` --> KO
Then I retry but no success. Seem that the script works only the first time of app lunch.

**Comment by rivaros** [comment]
Shame! It does not work with 1.4.12. Please reopen the issue.

**Comment by dks333** [comment]
same, not working with 1.4.6

**Comment by marcoj** [comment]
Same in 1.5.0

**Comment by billnbell** [comment]
I just delete Pods and rerun yarn ios and it seems to always work for me.

`pod deintegrate && pod install`

**Comment by TwistedMinda** [comment]
> I just delete Pods and rerun yarn ios and it seems to always work for me.
> 
> `pod deintegrate && pod install`

Perfect dude, thank you! This is the quickest! **Not even** a `yarn start --reset-cache` is needed

**Comment by lclarkg18** [comment]
Same issue, pod install is not fixing it consistently though.

**Comment by chdzma** [comment]
Same with the last version, android can't read the env variables and ios is cached all the time

**Comment by billnbell** [comment]
what canw e do to fix this?

**Comment by Rc85** [comment]
> I just delete Pods and rerun yarn ios and it seems to always work for me.
> 
> `pod deintegrate && pod install`

This is basically clean build folder. When you reinstall pods, it will clean out your build folder.

**Comment by nghiaklabs** [comment]
> Fixed in `1.4.12`

It's not working

**Comment by gCardinal** [comment]
Adding my voice to this issue. At least on iOS, this isn't currently working.

**Comment by engineerStuardo** [comment]
hey @gCardinal what do you mean by `Make sure the path to your .env file is an absolute path`?? What should I do exactly?

**Comment by billnbell** [comment]
Everyone: This module is pretty simple. It generates a file and puts it in Pods. It does that when you yarn install - and only if it is not already there. So you have 2 choices. 1. Delete Pods - then rerun `pod install` or 2. `pod deintegrate` and then `pod install` 

Got it?

**Comment by engineerStuardo** [comment]
@billnbell the problem is only on iOS that if I make a change on my .env file it doesn't read that change and keep the first one. I need to delete node_modules and until then reads the new one. Sorry I'm a beginner on this.

**Comment by gCardinal** [comment]
> hey @gCardinal what do you mean by `Make sure the path to your .env file is an absolute path`?? What should I do exactly?

I mean instead of pointing to files like so `../../.env`, I had to use the absolute path `/Users/my-user/dev/project-name/.env`.

I also did _not_ need to delete my pods when changing a value - I do however need to clean the project in XCode. I am also not using the [environment variable way to point to different files](https://github.com/luggit/react-native-config#different-environments). I had to do it [this way](https://github.com/luggit/react-native-config#different-environments), so in the end I have something like this in my Podfile:

```
CURRENT_DIRECTORY = Dir.pwd()
PROJECT_ROOT = File.expand_path("#{CURRENT_DIRECTORY}/../../../")
ENV_FILES = {
  'Debug' => "#{PROJECT_ROOT}/.env",
  'Debug-Staging' => "#{PROJECT_ROOT}/.env.stg",
  'Debug-Prod' => "#{PROJECT_ROOT}/.env.prd",
  'Release' => "#{PROJECT_ROOT}/.env.dev",
  'Release-Staging' => "#{PROJECT_ROOT}/.env.stg",
  'Release-Prod' => "#{PROJECT_ROOT}/.env.prd",
}

# Then, in my post install hook:

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'react-native-config'
        config.build_settings['ENVFILE'] = ENV_FILES[config.name]
      end
    end
  end
```

This was what finally worked for me, but as I said, when I change values, I need to clean the project. No other way around it that I could find.

**Comment by engineerStuardo** [comment]
Thank you so much @gCardinal 🥇

**Comment by jackkrone** [comment]
> @mickael-h Faced the same issue, fixed it by clearing the xcodederiveddata in your system.

This works for me. To be more specific, I added the following script to my package.json, which I run every time I change the contents of my .env file:

```
"deleteDerivedData": "rm -rf ${HOME}/Library/Developer/Xcode/DerivedData/*"
```

I am using different schemes in my project which means I have a .env.prod, .env.develop, and .env.qa file, the contents of which are copied into the main .env file when running the associated scheme. I always delete derived data before switching the scheme I'm running locally.

**Comment by arundevkv** [comment]
@jackkrone that worked for me. Thanks

**Comment by ronilitman** [comment]
works with `pod deintegrate && pod install`, but is there regular solution coming soon?

**Comment by toorandroidmaster** [comment]
> Faced the same issue, every time need to manually remove node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m.
> 
> Any updates on the handling?

i fixed this issue using this 
https://github.com/luggit/react-native-config/issues/698#issuecomment-1402764601

**Comment by Irfanwani** [comment]
Same issue with iOS still persists.

**Comment by billnbell** [comment]
Yeah to fix this correctly we need to add to the pipeline an env variable check or something "RESET_CONFIG=1" and then when building delete the file and re-generates. I am sure this is not a high priority - but the author of this package should see if there is a way to make this easier to regenerate the generated files.

**Comment by developerdanx** [comment]
This is still an issue. Seriously we don't have a good solution yet?

**Comment by billnbell** [comment]
I think they take PRs :)

**Comment by nathantew14** [comment]
I tried pretty much everything suggested here and it still doesn’t work...

**Comment by bodiavaleur** [comment]
Got it fixed by generating GeneratedDotEnv.m on every build

```
cp "${PROJECT_DIR}/../.env.production" "${PROJECT_DIR}/../.env"
"${SRCROOT}/../../../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/../.env" "${SRCROOT}/tmp.xcconfig"
"${SOURCE_ROOT}/../../../node_modules/react-native-config/ios/ReactNativeConfig/BuildDotenvConfig.rb" "${SOURCE_ROOT}/../.env" "${SOURCE_ROOT}/../../../node_modules/react-native-config/ios/ReactNativeConfig/"
^ Add this line and change relative path to your node_modules
```

**Comment by nathantew14** [comment]
i gave up and started using expo. it just... works! never turning back.

**Comment by Biplovkumar** [comment]
I added `    "clear": "rm -f node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m",
` in Package.json scripts. it is working fine. but is is a temporary solution.
I am using 1.5.1 and still facing same issue. Please resolve.

**Comment by joaquinvaz** [comment]
I'm having this issue, any solution? only running "Clean Build Folder" in Xcode does work

**Comment by nathantew14** [comment]
> I'm having this issue, any solution? only running "Clean Build Folder" in Xcode does work

Just use expo

**Comment by rolfen** [comment]
I found the solution. I format my disk and reinstall the OS and the variable updates. Works every time.

**Comment by Biplovkumar** [comment]
> Just u

This is not a solution

**Comment by bigriot** [comment]
> Anything speaking against doing it like this:
> 
> ```
> rm -rf "${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m"
> cp "${PROJECT_DIR}/../.env.development" "${PROJECT_DIR}/../.env"  
> "${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"
> ```

I think this is pretty much it. A simple update to the documentation would suffice IMHO.

**Comment by endrits079** [comment]
Why is this closed when this issue apparently still exists?

**Comment by phuocantd** [comment]
> > @mickael-h Faced the same issue, fixed it by clearing the xcodederiveddata in your system.
> 
> This works for me. To be more specific, I added the following script to my package.json, which I run every time I change the contents of my .env file:
> 
> ```
> "deleteDerivedData": "rm -rf ${HOME}/Library/Developer/Xcode/DerivedData/*"
> ```
> 
> I am using different schemes in my project which means I have a .env.prod, .env.develop, and .env.qa file, the contents of which are copied into the main .env file when running the associated scheme. I always delete derived data before switching the scheme I'm running locally.

It not work for me

**Comment by samipshresthaq** [comment]
> > Faced the same issue, every time need to manually remove node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m.
> > Any updates on the handling?
> 
> i fixed this issue using this [#698 (comment)](https://github.com/lugg/react-native-config/issues/698#issuecomment-1402764601)

This worked for me! Apr 6 2024

**Comment by sergsar** [comment]
The issue still exists on iOS and deleting .env files every build isn't a good idea at all

**Comment by arelstone** [comment]
The problem is not the env file nor the xcode cache. The problem is that a file is written into the ios and android directories of this library. 

A workaround that I am using is to create a `prestart` script in our package.json that deleted thoes files
```json
"prestart": "rm -f node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m node_modules/react-native-config/android/build/generated/source/buildConfig/debug/com/lugg/RNCConfig/BuildConfig.java node_modules/react-native-config/android/build/generated/source/buildConfig/release/com/lugg/RNCConfig/BuildConfig.java"
```

This requires us to restart the metro bundler when we've updated the env - Which to me makes sense.

**Comment by valerii-link** [comment]
https://github.com/lugg/react-native-config/issues/788#issuecomment-2097807290

**Comment by eisodev** [comment]
From reading the comments, this works for me when I change a custom ENV variable URL from server to localhost for running a local backend and then starting my React Native app:

```
"refreshENVforiOS": "touch \"node_modules/react-native-config/ios/ReactNativeConfig/BuildDotenvConfig.rb\"",
    "ios": "npm run refreshENVforiOS && react-native run-ios --terminal terminal",
   ```
   
   npm run ios 
   
   Starts a new terminal window (like it used to before newer React Native versions). And it now reads the correct env variables that I updated in the .env file in the project root.

**Comment by Yangeok** [comment]
Script `prestart` is the charm! Thank you

**Comment by khanh21011999** [comment]
You saved me from stupid dog shit I faced 2 days

> [#788 (comment)](https://github.com/lugg/react-native-config/issues/788#issuecomment-2097807290)

You saved me from stupid dog shit 2 day, thank god
