### ISSUE TITLE
[IOS] `use of undeclared identifier 'ReactNativeConfig'`

### ISSUE THREAD

**Issue by OlivierDijkstra** [luggit/react-native-config#708]
I've been having this issue for a couple days now and not sure if I'm able to figure out exactly what it wrong.

I am trying to access the .env values from inside `ios/<app>/AppDelegate.mm`. When, for example, trying to log the current environment variables using 

```
#import "ReactNativeConfig.h"
NSLog(@"ReactNativeConfig values: %@", [ReactNativeConfig env]);
```

The build process errors out with `use of undeclared identifier 'ReactNativeConfig'`.
If I run `npx react-native config` I can see `react-native-config` present and also in the auto-linking prompt when running `pod install`. The package is also available in javascript so it seems to load fine. I do have expo installed so that might have something to do with it?

versions:
```
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-config": "^1.4.11",
    "expo": "^47.0.0",
```

Could this be related to: https://github.com/luggit/react-native-config/issues/667 ?, commenting out `#import <react/config/ReactNativeConfig.h>` builds fine but as soon as I try to access anything ReactNativeConfig related it errors out like above, so not sure if there are any name overlapping problems.

**Comment by philpettican118** [comment]
Hi @OlivierDijkstra , I'm pretty sure this is related to #667 which should be fixed in https://github.com/luggit/react-native-config/releases/tag/v1.5.0

**Comment by danieldanielecki** [comment]
Make sure to put your `#import "RNCConfig.h"` **above** `#if RCT_NEW_ARCH_ENABLED` in imports. Otherwise, you'll still see this error and try to Google wtf :-))

**Comment by OlivierDijkstra** [comment]
Thanks for the responses! I'll close this issue since we've also found a way to accomplish what we want without using React Native Config. Good to hear it's fixed however!
